# fly.toml app configuration file generated for test-consumer-dev on 2023-11-18T14:48:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-consumer"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
